### ISSUE TITLE
Compatibility with GLPI 10.0.2 version

### ISSUE THREAD

**Issue by lzkill** [MartialSeron/glpi-api#12]
Hi folks. Thanks for the great job!

Is this client compatible with GLPI 10.0.2 version? I'm getting an error when I try to upload a file:

**The calling code:**
```javascript
const path = require('path');
const GlpiApi = require('glpi-api');

async function test() {
    const config = {
        app_token: 'XXX',
        apiurl: 'XXX',
        user_token: 'XXX',
    };

    const glpi = new GlpiApi(config);

    await glpi.initSession();

    const file = path.resolve(__dirname, 'test.txt')
    const result = await glpi.upload({
        filePath: file,
        fileName: 'my_custom_name.txt',
        fileType: 'plain/text',
    }, 'test');

    glpi.killSession();
}

async function start() {
    await test();
}

start();
```

**The error (pt_BR):**

```
> glpi-rest@1.0.0 start
> node -r esm index.js

/home/lzkill/Projects/glpi-rest/node_modules/glpi-api/glpi.js:185
      throw new ServerError(err);
            ^

ServerError: ERROR_BAD_ARRAY
    at /home/lzkill/Projects/glpi-rest/node_modules/glpi-api/glpi.js:185:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async test (/home/lzkill/Projects/glpi-rest/index.js:16:20)
    at async start (/home/lzkill/Projects/glpi-rest/index.js:32:5) {
  code: 400,
  comment: 'o parâmetro de entrada deve ser um vetor de objetos; ver documentação em seu navegador em https://XXX/apirest.php/#ERROR_BAD_ARRAY'
}
```

**Comment by mrtl-srn** [comment]
Hi. Thanks for your feedback.

I didn't tested it on glpi 10 yet but it is planned soon.
